# Generated by Django 5.2.8 on 2025-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_country_user_phone_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('delivery', 'Delivery Staff')], default='customer', max_length=20),
        ),
    ]
