# Generated by Django 4.2.9 on 2025-11-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='Dembel Main Street.', max_length=100),
        ),
    ]
