# Generated by Django 4.2.9 on 2025-11-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
