# Generated by Django 4.2.9 on 2025-11-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
