# Generated by Django 4.2.9 on 2025-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_conversationmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vendor_confirmation',
            field=models.BooleanField(blank=True, help_text='Has the vendor confirmed availability of the material?', null=True),
        ),
    ]
