# Generated by Django 4.2.9 on 2025-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_vendor_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='vendor_confirmation',
            field=models.BooleanField(blank=True, help_text='Has the vendor confirmed availability of the material?', null=True),
        ),
    ]
