# Generated by Django 4.2.9 on 2025-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cartorderproducts_vendor_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='admin_verified',
            field=models.BooleanField(blank=True, default=False, help_text='Has the admin verified this order?', null=True),
        ),
        migrations.AddField(
            model_name='cartorderproducts',
            name='admin_verified',
            field=models.BooleanField(blank=True, default=False, help_text='Has the admin verified this order?', null=True),
        ),
    ]
