# Generated by Django 4.2.9 on 2025-11-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cartorder_admin_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='admin_verified',
        ),
        migrations.RemoveField(
            model_name='cartorderproducts',
            name='admin_verified',
        ),
    ]
