# Generated by Django 4.2.9 on 2025-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cartorder_admin_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='vendor_confirmation',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not_available', 'Not Available')], default='pending', max_length=30),
        ),
    ]
