# Generated by Django 4.2.9 on 2025-11-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cartorder_vendor_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
