# Generated by Django 4.2.9 on 2025-11-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartorderproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
