# Generated by Django 5.2.8 on 2025-12-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_discounted_price_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
    ]
