# Generated by Django 5.2.8 on 2025-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
