# Generated by Django 5.2.8 on 2025-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cartorder_shipping_cost_cartorder_shipping_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
