# Generated by Django 5.2.8 on 2025-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cartorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='vendor_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
