# Generated by Django 5.2.8 on 2025-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cartorderproducts_vendor_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproducts',
            name='customer_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
